{% set name = "chemcoord" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemcoord-{{ version }}.tar.gz
  sha256: 232134bc7f0c66835aaa9147d7524f42467ef612f74af22c0f117c520359ce6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numba >=0.35
    - numpy >=1.0
    - pandas >=1.0,<2
    - pymatgen
    - python >=3.6
    - scipy
    - six
    - sortedcontainers
    - sympy

test:
  imports:
    - chemcoord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcocdawc/chemcoord
  summary: Python module for dealing with chemical coordinates.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ghutchis
    - mcocdawc
