{% set name = "chemcoord" %}
{% set version = "2.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemcoord-{{ version }}.tar.gz
  sha256: f725a3da458b5e2e98b3f78890f1b5b111d1c5ce15e40224d9fa4dc989953a4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=64
    - python {{ python_min }}
  run:
    - attrs
    - cattrs
    - joblib
    - numba >=0.66
    - numpy >=1.23
    - ordered-set
    - pandas >=2.0
    - pymatgen
    - python >={{ python_min }}
    - pyyaml
    - sortedcontainers
    - sympy
    - typing_extensions

test:
  imports:
    - chemcoord
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mcocdawc/chemcoord
  summary: Python module for dealing with chemical coordinates.
  license: LGPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ghutchis
    - mcocdawc
